"""Hatchling build hook: stamp build-time provenance into the built ``omc`` package.

Runs at build time (``uv tool install`` / ``uv build`` / ``hatch build``) for both a
local-checkout install (``uv tool install <repo>``) and a git-URL install
(``uv tool install git+…``) — in both cases uv materializes a real working tree, so
the git probes below resolve the actual branch/commit/source. A worktree checkout
whose ``.git`` pointer file targets a path that exists (the normal host case) probes
fine; inside containers that copied only the worktree, probes fail soft to "unknown".

We do NOT write into the source tree (that would dirty the working copy on every
editable ``uv run``/``uv sync`` and the committed ``_buildinfo.py`` would never stay
the ``"unknown"`` fallback). Instead we write the stamped module to a temp file and
``force_include`` it into the artifact as ``omc/_buildinfo.py``, overriding the
checked-in fallback only inside the built wheel/sdist.

Provenance resolution order (first that yields a value wins, else ``"unknown"``):
  1. ``OMC_BUILD_BRANCH`` / ``OMC_BUILD_COMMIT`` / ``OMC_BUILD_SOURCE`` env vars;
  2. ``git`` in the source tree (when ``<root>/.git`` is present);
  3. ``"unknown"``.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Any

try:  # hatchling is a BUILD dep, absent from the runtime venv. Guard so the pure
    # provenance helpers below stay importable for unit tests (`uv run pytest`), while
    # the build env (uv build / uv tool install) gets the real base class.
    from hatchling.builders.hooks.plugin.interface import BuildHookInterface
except ModuleNotFoundError:  # pragma: no cover - exercised only outside the build env
    BuildHookInterface = object  # type: ignore[assignment, misc]


class BuildInfoHook(BuildHookInterface):
    """Generate ``omc/_buildinfo.py`` and force-include it into the build."""

    PLUGIN_NAME = "custom"  # ignored for the in-tree custom hook, but explicit/clear.

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        branch, commit, source = _resolve(Path(self.root))
        # Write to a temp file (NOT the source tree) and inject it into the artifact.
        fd, tmp = tempfile.mkstemp(prefix="omc-buildinfo-", suffix=".py")
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(_render(branch, commit, source))
        # force_include maps a real path -> the path it takes inside the artifact, so
        # this replaces the checked-in src/omc/_buildinfo.py within the wheel/sdist.
        build_data.setdefault("force_include", {})[tmp] = "omc/_buildinfo.py"


def _resolve(root: Path) -> tuple[str, str, str]:
    """(branch, commit, source) — for each field: env var → git probe → 'unknown'."""
    has_git = (root / ".git").exists()

    def field(env_key: str, *git_args: str) -> str:
        env_val = os.environ.get(env_key)
        if env_val:
            return _redact(env_val)
        if has_git:
            git_val = _redact(_git(root, *git_args))
            if git_val:
                return git_val
        return "unknown"

    return (
        field("OMC_BUILD_BRANCH", "rev-parse", "--abbrev-ref", "HEAD"),
        field("OMC_BUILD_COMMIT", "rev-parse", "--short", "HEAD"),
        field("OMC_BUILD_SOURCE", "remote", "get-url", "origin"),
    )


def _git(root: Path, *args: str) -> str:
    """Run a read-only ``git`` probe (array form, no shell); '' on any failure."""
    try:
        cp = subprocess.run(
            ["git", "-C", str(root), *args],
            capture_output=True,
            text=True,
            errors="replace",
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return ""
    return cp.stdout.strip()


def _redact(url: str) -> str:
    """Strip ``user:password@`` credentials from a URL before it lands in the artifact.

    Only a form WITH a colon is a credential — a bare ``user@host`` is an ssh login
    (e.g. ``git@github.com:…``) and MUST be preserved verbatim, so the regex requires
    the ``:`` and leaves bare-user URLs untouched.
    """
    return re.sub(r"://[^/@]+:[^/@]+@", "://", url)


def _render(branch: str, commit: str, source: str) -> str:
    return (
        "# Auto-generated by hatch_build.py at build time; do not edit.\n"
        f"BRANCH = {json.dumps(branch)}\n"
        f"COMMIT = {json.dumps(commit)}\n"
        f"SOURCE = {json.dumps(source)}\n"
    )
