"""Idle notifications (COPS-988): sessions that need attention ping the user.

Detection is per-harness — providers DESCRIBE their wiring
(`Provider.notification_setup`) and `wire_worktree` materializes it at
`omc start`. Delivery is shared: every hook invokes
`omc internal notify --provider <name>`, which normalizes the payload and
dispatches on `notifications.backend` ("macos" → osascript;
"file://<abs path>" → one tab-separated line, tail-friendly). Invariant:
notifications never break work — failures warn at most; the sink exits 0.
Providers whose harness posts its own desktop notification (claude) skip
the macos backend — file backends always log.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

from .config import store
from .config.schema import GlobalConfig
from .errors import ConfigError, OmcError
from .providers.registry import get_provider
from .toolctx import ToolContext

GENERIC_BODY = "needs your attention"
_CTRL = re.compile(r"[\x00-\x1f\x7f]")
_MARKER = "// generated by omc"


def sink_argv(provider_name: str) -> list[str]:
    """The command every harness hook invokes (omc is on PATH as a uv tool)."""
    return ["omc", "internal", "notify", "--provider", provider_name]


def deliver(
    cfg: GlobalConfig, *, ctx: ToolContext, provider: str, event: str, body: str, cwd: str
) -> None:
    """Send one notification to the configured backend. Never raises."""
    slug = ctx.env.get("OMC_SLUG") or Path(cwd).resolve().name
    backend = cfg.notifications.backend
    if backend == "macos":
        if not _notifies_natively(provider):
            _deliver_macos(ctx, slug, body)
    elif backend.startswith("file://"):
        _deliver_file(Path(backend[len("file://") :]), slug, provider, event, body)


def _notifies_natively(provider_name: str) -> bool:
    """macos-backend suppression check: a harness that posts its own clickable
    desktop notification (claude) makes omc's osascript ping a duplicate.
    Unknown names (production is argparse-guarded; tests call deliver directly)
    count as not-native — deliver rather than drop."""
    try:
        return get_provider(provider_name).notifies_natively()
    except OmcError:
        return False


def _applescript_str(s: str) -> str:
    """AppleScript string literal — payload text is data, never code."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _deliver_macos(ctx: ToolContext, slug: str, body: str) -> None:
    if sys.platform != "darwin":
        return  # backend seam: notify-send etc. are later drop-ins
    # Clean control chars before AppleScript escaping (notifications are single-line)
    clean_body = _clean(body)
    clean_slug = _clean(slug)
    script = (
        f"display notification {_applescript_str(clean_body)}"
        f" with title {_applescript_str(f'omc: {clean_slug}')}"
    )
    try:
        ctx.run(["osascript", "-e", script], timeout=10)
    except (OSError, subprocess.TimeoutExpired):
        pass  # notifications never break work


def _clean(column: str) -> str:
    """One log column: control chars (incl. tab/newline) become spaces."""
    return _CTRL.sub(" ", column)


def _deliver_file(path: Path, slug: str, provider: str, event: str, body: str) -> None:
    ts = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    cols = [ts, _clean(slug), _clean(provider), _clean(event), _clean(body)]
    try:
        with open(path, "a", encoding="utf-8") as fh:
            fh.write("\t".join(cols) + "\n")  # one write per line: append-atomic enough
    except OSError as exc:
        print(f"omc notify: cannot append to {path}: {exc}", file=sys.stderr)


def _warn(msg: str) -> None:
    print(f"· notify wiring: {msg}", file=sys.stderr, flush=True)


def merge_claude_settings(existing_text: str, ours_text: str) -> str | None:
    """Append our hook groups into an existing settings JSON; None when the
    existing file can't be treated as settings (invalid JSON / wrong shapes).
    Idempotent: events already containing our command are left untouched."""
    try:
        existing = json.loads(existing_text)
    except json.JSONDecodeError:
        return None
    if not isinstance(existing, dict):
        return None
    hooks = existing.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        return None
    for event, groups in json.loads(ours_text)["hooks"].items():
        entries = hooks.setdefault(event, [])
        if not isinstance(entries, list):
            return None
        ours_cmd = groups[0]["hooks"][0]["command"]
        present = any(
            hook.get("command") == ours_cmd
            for group in entries
            if isinstance(group, dict)
            for hook in group.get("hooks", [])
            if isinstance(hook, dict)
        )
        if not present:
            entries.extend(groups)
    return json.dumps(existing, indent=2) + "\n"


def wire_worktree(provider, worktree: Path) -> list[str]:
    """Materialize the provider's notification wiring in the worktree.
    Returns the relative paths written/updated. Failures warn and skip —
    wiring must never block `omc start`. The merge path is load-bearing:
    wt's copy-ignored hook may have copied the PRIMARY checkout's
    settings.local.json into this worktree before we run."""
    written: list[str] = []
    for rel, content in provider.notification_setup(sink_argv(provider.name)).items():
        target = worktree / rel
        try:
            if target.name == "settings.local.json" and target.exists():
                existing = target.read_text()
                merged = merge_claude_settings(existing, content)
                if merged is None:
                    _warn(f"{rel} is not valid settings JSON — leaving it alone")
                    continue
                if merged != existing:
                    target.write_text(merged)
                    written.append(rel)
            elif target.exists():
                existing = target.read_text()
                if existing.split("\n", 1)[0].startswith(_MARKER):
                    if existing != content:
                        target.write_text(content)
                        written.append(rel)
                else:
                    if existing != content:
                        _warn(f"{rel} exists with foreign content — leaving it alone")
                continue
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content)
                written.append(rel)
        except (OSError, ValueError, KeyError, IndexError) as exc:
            # ValueError covers UnicodeDecodeError (non-UTF-8 existing files) and
            # any stray JSONDecodeError; KeyError guards ours_text's ["hooks"]
            # lookup in merge_claude_settings, though ours_text is our own
            # generated content so that path is theoretical; IndexError guards
            # the same call's groups[0]/["hooks"][0] indexing against an
            # empty hook group (also theoretical for our own content).
            _warn(f"could not write {rel}: {exc}")
    return written


def payload_from_claude(stdin_text: str) -> tuple[str, str]:
    """Claude hooks pass JSON on stdin; body comes from its `message` field.
    `last_assistant_message` is deliberately ignored — no transcript content
    reaches the notification center or log."""
    try:
        data = json.loads(stdin_text or "{}")
    except json.JSONDecodeError:
        return "unknown", GENERIC_BODY
    if not isinstance(data, dict):
        return "unknown", GENERIC_BODY
    event = str(data.get("hook_event_name") or "unknown")
    if event == "Stop":
        return event, "turn complete"
    return event, str(data.get("message") or GENERIC_BODY)


def payload_from_codex(arg: str | None) -> tuple[str, str]:
    # codex passes ONE JSON argument to its notify program; the only event it
    # emits today is agent-turn-complete (verified July 2026).
    try:
        data = json.loads(arg or "")
    except json.JSONDecodeError:
        return "unknown", GENERIC_BODY
    if not isinstance(data, dict):
        return "unknown", GENERIC_BODY
    event = str(data.get("type") or "unknown")
    return event, "turn complete" if event == "agent-turn-complete" else GENERIC_BODY


def run_notify(ctx: ToolContext, args: argparse.Namespace) -> int:
    """`omc internal notify` body. Always exit 0 — a notification must never
    fail a session; usage errors (exit 2) are handled by the dispatcher."""
    try:
        cfg = store.load_global(ctx.home)
    except ConfigError:
        return 0
    if cfg is None or not cfg.notifications.enabled:
        return 0  # global kill switch — even for already-wired worktrees
    if args.provider == "claude":
        # hooks pipe the payload via stdin; a TTY means a human poking at it
        text = "" if sys.stdin.isatty() else sys.stdin.read()
        event, body = payload_from_claude(text)
    elif args.provider == "codex":
        event, body = payload_from_codex(args.payload)
    else:  # opencode: the generated plugin passes explicit flags
        event, body = (args.event or "unknown", args.message or GENERIC_BODY)
    deliver(cfg, ctx=ctx, provider=args.provider, event=event, body=body, cwd=os.getcwd())
    return 0
