from __future__ import annotations

from .base import Provider


class OpencodeProvider(Provider):
    name = "opencode"

    def models(self):
        return []  # free-text `provider/model` entry

    def headless_argv(self, prompt, *, model, allowed_tools=None, session_name=""):
        argv = ["opencode", "run"]
        if model:
            argv += ["-m", model]
        argv.append(prompt)
        return argv

    def session_argv(self, *, session_name, model, seed, notify_sink_argv=None):
        # Interactive `opencode [project]` — the positional is a DIRECTORY, not a
        # prompt; the seed rides on --prompt. No session-name flag exists.
        argv = ["opencode"]
        if model:
            argv += ["-m", model]
        argv += ["--prompt", seed]
        return argv

    def notification_setup(self, sink_argv):
        # A generated project plugin (no npm deps): opencode loads
        # .opencode/plugin/*.js and calls `event` for every bus event. The
        # "generated by omc" first line is the marker wire_worktree checks:
        # present → ours, safe to overwrite on template changes; absent →
        # foreign, left alone.
        cmd = " ".join(sink_argv)
        plugin = f"""\
// generated by omc — idle notifications (COPS-988); safe to delete.
export const OmcNotify = async ({{ $ }}) => ({{
  event: async ({{ event }}) => {{
    const bodies = {{
      "session.idle": "session ready",
      "permission.asked": "permission needed",
      "session.error": "session error",
    }};
    const body = bodies[event.type];
    if (!body) return;
    await $`{cmd} --event ${{event.type}} --message ${{body}}`.quiet().nothrow();
  }},
}});
"""
        return {".opencode/plugin/omc-notify.js": plugin}

    def title_env(self):
        return {"OPENCODE_DISABLE_TERMINAL_TITLE": "1"}

    def install_hint(self):
        return "npm install -g opencode-ai"
